include theos/makefiles/common.mk

BUNDLE_NAME = PushRecordToggle
PushRecordToggle_FILES = Switch.x
PushRecordToggle_FRAMEWORKS = UIKit
PushRecordToggle_LIBRARIES = flipswitch
PushRecordToggle_INSTALL_PATH = /Library/Switches

include $(THEOS_MAKE_PATH)/bundle.mk